import PDFDocument from "pdfkit";
import type { Fund } from "@shared/schema";

const NAVY = "#0f172a";
const TEAL = "#0f766e";
const LIGHT_GRAY = "#f8fafc";
const MID_GRAY = "#e2e8f0";
const DARK_TEXT = "#1e293b";
const MUTED_TEXT = "#64748b";
const GREEN = "#16a34a";
const YELLOW = "#ca8a04";
const RED = "#dc2626";

function bandColor(band: string | null): string {
  if (band === "STRONG") return GREEN;
  if (band === "REVIEW") return YELLOW;
  return RED;
}

export function generatePdfReport(
  allFunds: Fund[],
  stats: { total: number; avgScore: number; strongCount: number; weakCount: number },
  categoryFilter?: string[]
): Buffer {
  const doc = new PDFDocument({ size: "LETTER", margin: 50, bufferPages: true });
  const chunks: Buffer[] = [];
  doc.on("data", (chunk: Buffer) => chunks.push(chunk));

  // Filter funds by category if needed
  let funds = allFunds;
  if (categoryFilter && categoryFilter.length > 0) {
    funds = allFunds.filter(f => f.categoryName && categoryFilter.includes(f.categoryName));
  }

  // Group by category
  const categoryMap = new Map<string, Fund[]>();
  for (const f of funds) {
    const cat = f.categoryName || "Uncategorized";
    if (!categoryMap.has(cat)) categoryMap.set(cat, []);
    categoryMap.get(cat)!.push(f);
  }

  // Sort categories by avg score descending
  const categories = Array.from(categoryMap.entries())
    .map(([name, catFunds]) => {
      const scores = catFunds.filter(f => f.score !== null).map(f => f.score!);
      const avg = scores.length > 0 ? scores.reduce((a, b) => a + b, 0) / scores.length : 0;
      return { name, funds: catFunds, avgScore: avg };
    })
    .sort((a, b) => b.avgScore - a.avgScore);

  // Recalculate stats for filtered set
  const filteredScored = funds.filter(f => f.score !== null);
  const filteredStats = categoryFilter
    ? {
        total: filteredScored.length,
        avgScore: filteredScored.length > 0
          ? filteredScored.reduce((a, f) => a + f.score!, 0) / filteredScored.length
          : 0,
        strongCount: filteredScored.filter(f => f.score! >= 80).length,
        weakCount: filteredScored.filter(f => f.score! < 60).length,
      }
    : stats;

  // ====== PAGE 1: COVER ======
  doc.rect(0, 0, doc.page.width, doc.page.height).fill(NAVY);

  doc.fill("#ffffff")
    .font("Helvetica-Bold")
    .fontSize(36)
    .text("Fund Scoring Report", 50, 180, { align: "center" });

  const dateStr = new Date().toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  doc.font("Helvetica")
    .fontSize(16)
    .fillColor(TEAL)
    .text(`${dateStr} · ${filteredStats.total} Funds Scored`, 50, 230, { align: "center" });

  if (categoryFilter && categoryFilter.length > 0) {
    doc.fontSize(12)
      .fillColor("#94a3b8")
      .text(`Categories: ${categoryFilter.join(", ")}`, 50, 260, { align: "center" });
  }

  // KPI boxes
  const kpiY = 340;
  const kpiWidth = 115;
  const kpiGap = 15;
  const totalKpiWidth = 4 * kpiWidth + 3 * kpiGap;
  const kpiStartX = (doc.page.width - totalKpiWidth) / 2;

  const kpis = [
    { label: "Total Funds", value: String(filteredStats.total) },
    { label: "Avg Score", value: filteredStats.avgScore.toFixed(1) },
    { label: "% Strong", value: `${filteredStats.total > 0 ? ((filteredStats.strongCount / filteredStats.total) * 100).toFixed(1) : "0"}%` },
    { label: "% Weak", value: `${filteredStats.total > 0 ? ((filteredStats.weakCount / filteredStats.total) * 100).toFixed(1) : "0"}%` },
  ];

  kpis.forEach((kpi, i) => {
    const x = kpiStartX + i * (kpiWidth + kpiGap);
    doc.roundedRect(x, kpiY, kpiWidth, 70, 6).fill("#1e293b");
    doc.fillColor(TEAL).font("Helvetica-Bold").fontSize(22).text(kpi.value, x, kpiY + 14, { width: kpiWidth, align: "center" });
    doc.fillColor("#94a3b8").font("Helvetica").fontSize(9).text(kpi.label, x, kpiY + 44, { width: kpiWidth, align: "center" });
  });

  // Footer
  doc.fillColor("#475569")
    .font("Helvetica")
    .fontSize(9)
    .text("Generated by FundScore Dashboard", 50, doc.page.height - 80, { align: "center" });

  // ====== CATEGORY PAGES ======
  for (const cat of categories) {
    doc.addPage({ margin: 50 });
    addPageHeader(doc, cat.name);

    const catFunds = cat.funds.filter(f => f.score !== null).sort((a, b) => (b.score || 0) - (a.score || 0));
    const catScores = catFunds.map(f => f.score!);
    const catAvg = catScores.length > 0 ? catScores.reduce((a, b) => a + b, 0) / catScores.length : 0;
    const best = catFunds[0];
    const worst = catFunds[catFunds.length - 1];

    // Category summary
    let y = doc.y + 5;
    doc.fillColor(DARK_TEXT).font("Helvetica").fontSize(10);
    doc.text(`Funds: ${catFunds.length}  ·  Avg Score: ${catAvg.toFixed(1)}  ·  Best: ${best?.symbol || "—"} (${best?.score?.toFixed(1) || "—"})  ·  Worst: ${worst?.symbol || "—"} (${worst?.score?.toFixed(1) || "—"})`, 50, y);

    y = doc.y + 12;

    // Table header
    const cols = [
      { label: "Symbol", x: 50, w: 80 },
      { label: "Name", x: 130, w: 190 },
      { label: "Score", x: 320, w: 55 },
      { label: "Band", x: 375, w: 65 },
      { label: "Expense Ratio", x: 440, w: 80 },
    ];

    doc.rect(50, y, 470, 18).fill(NAVY);
    doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(8);
    for (const col of cols) {
      doc.text(col.label, col.x + 4, y + 5, { width: col.w - 8 });
    }
    y += 18;

    // Table rows (top 10)
    const top10 = catFunds.slice(0, 10);
    for (let i = 0; i < top10.length; i++) {
      const fund = top10[i];
      const rowColor = i % 2 === 0 ? "#ffffff" : LIGHT_GRAY;
      const rowH = 16;

      if (y + rowH > doc.page.height - 60) {
        addPageFooter(doc);
        doc.addPage({ margin: 50 });
        addPageHeader(doc, `${cat.name} (cont.)`);
        y = doc.y + 5;
      }

      doc.rect(50, y, 470, rowH).fill(rowColor);

      // Band indicator dot
      doc.circle(54, y + rowH / 2, 3).fill(bandColor(fund.scoreBand));

      doc.fillColor(DARK_TEXT).font("Helvetica-Bold").fontSize(8);
      doc.text(fund.symbol, cols[0].x + 10, y + 4, { width: cols[0].w - 14 });

      doc.fillColor(DARK_TEXT).font("Helvetica").fontSize(8);
      doc.text(fund.name.substring(0, 40), cols[1].x + 4, y + 4, { width: cols[1].w - 8 });

      doc.fillColor(bandColor(fund.scoreBand)).font("Helvetica-Bold").fontSize(8);
      doc.text(fund.score?.toFixed(1) || "—", cols[2].x + 4, y + 4, { width: cols[2].w - 8 });

      doc.fillColor(MUTED_TEXT).font("Helvetica").fontSize(8);
      doc.text(fund.scoreBand || "—", cols[3].x + 4, y + 4, { width: cols[3].w - 8 });

      doc.fillColor(DARK_TEXT).font("Helvetica").fontSize(8);
      doc.text(
        fund.netExpenseRatio !== null ? `${(fund.netExpenseRatio * 100).toFixed(2)}%` : "—",
        cols[4].x + 4, y + 4, { width: cols[4].w - 8 }
      );

      y += rowH;
    }

    addPageFooter(doc);
  }

  // ====== METHODOLOGY PAGE ======
  doc.addPage({ margin: 50 });
  addPageHeader(doc, "Methodology");

  let my = doc.y + 10;

  doc.fillColor(DARK_TEXT).font("Helvetica-Bold").fontSize(12);
  doc.text("Scoring Approach", 50, my);
  my = doc.y + 6;

  doc.fillColor(DARK_TEXT).font("Helvetica").fontSize(10).lineGap(3);
  doc.text(
    "Each fund is scored on a 0–100 scale using percentile-rank methodology within its Morningstar category. " +
    "Metrics are weighted differently for passive (index) and active funds, reflecting the distinct characteristics that drive value in each investment style.",
    50, my, { width: 470 }
  );
  my = doc.y + 14;

  // Passive metrics
  doc.fillColor(TEAL).font("Helvetica-Bold").fontSize(11);
  doc.text("Passive (Index) Fund Weights", 50, my);
  my = doc.y + 6;
  doc.fillColor(DARK_TEXT).font("Helvetica").fontSize(9).lineGap(2);
  const passiveWeights = [
    "Net Expense Ratio: 40%",
    "Tracking Error (3Y/5Y/10Y): 30% total",
    "R-Squared (5Y): 5%",
    "AUM: 6%",
    "Downside Capture (5Y/10Y): 5%",
    "Max Drawdown (5Y/10Y): 4%",
  ];
  for (const w of passiveWeights) {
    doc.text(`  •  ${w}`, 50, my, { width: 470 });
    my = doc.y + 1;
  }
  my = doc.y + 10;

  // Active metrics
  doc.fillColor(TEAL).font("Helvetica-Bold").fontSize(11);
  doc.text("Active Fund Weights", 50, my);
  my = doc.y + 6;
  doc.fillColor(DARK_TEXT).font("Helvetica").fontSize(9).lineGap(2);
  const activeWeights = [
    "Net Expense Ratio: 25%",
    "Information Ratio (3Y/5Y/10Y): 20% total",
    "Sortino Ratio (3Y/5Y/10Y): 20% total",
    "Downside Capture (5Y/10Y): 10%",
    "Max Drawdown (5Y/10Y): 10%",
    "Upside Capture (5Y/10Y): 11%",
    "Total Returns (3Y/5Y/10Y): 4%",
  ];
  for (const w of activeWeights) {
    doc.text(`  •  ${w}`, 50, my, { width: 470 });
    my = doc.y + 1;
  }
  my = doc.y + 14;

  // Score bands
  doc.fillColor(TEAL).font("Helvetica-Bold").fontSize(11);
  doc.text("Score Band Definitions", 50, my);
  my = doc.y + 8;

  const bands = [
    { label: "STRONG", range: "80 – 100", desc: "Top-performing fund in its category. Recommended for continued/new allocation.", color: GREEN },
    { label: "REVIEW", range: "60 – 79", desc: "Acceptable performance but warrants monitoring. Evaluate alternatives.", color: YELLOW },
    { label: "WEAK", range: "0 – 59", desc: "Underperforming relative to peers. Consider replacement.", color: RED },
  ];

  for (const band of bands) {
    doc.circle(58, my + 5, 4).fill(band.color);
    doc.fillColor(DARK_TEXT).font("Helvetica-Bold").fontSize(10);
    doc.text(`${band.label} (${band.range})`, 68, my, { width: 440 });
    my = doc.y + 2;
    doc.fillColor(MUTED_TEXT).font("Helvetica").fontSize(9);
    doc.text(band.desc, 68, my, { width: 440 });
    my = doc.y + 8;
  }

  addPageFooter(doc);

  // Add page numbers
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    doc.fillColor(MUTED_TEXT).font("Helvetica").fontSize(8);
    doc.text(`Page ${i + 1} of ${range.count}`, 50, doc.page.height - 35, {
      width: doc.page.width - 100,
      align: "center",
    });
  }

  doc.end();

  return Buffer.concat(chunks);
}

function addPageHeader(doc: PDFKit.PDFDocument, title: string) {
  doc.rect(0, 0, doc.page.width, 45).fill(NAVY);
  doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(14).text(title, 50, 15);
  doc.fillColor(TEAL).font("Helvetica").fontSize(8).text("FundScore Report", doc.page.width - 150, 18, { width: 100, align: "right" });
  doc.y = 55;
}

function addPageFooter(doc: PDFKit.PDFDocument) {
  const y = doc.page.height - 50;
  doc.moveTo(50, y).lineTo(doc.page.width - 50, y).strokeColor(MID_GRAY).lineWidth(0.5).stroke();
}
